### ISSUE TITLE
How to find value of AppToCheckiOS?

### ISSUE THREAD

**Issue by phuongtruongincepit** [the16bitgamer/Unity_Android_iOS_App_Detection#1]
In file CheckInstalledApp.cs, in line 14:
public string AppToCheckiOS = "SixteenBitApp00";
I don't know where to find out "SixteenBitApp00". For example, If I want to check if another app such as Youtube, Twitter, ect. was installed, can you tell me how to find the value for that string AppToCheckiOS.

**Comment by the16bitgamer** [comment]
I gave the code explanation in the [Checking iOS Apps](https://github.com/the16bitgamer/Unity_Android_iOS_App_Detection#checking-ios-apps) section. Please re-review that for details for implementation. However I will explain how the theory works.

Unlike in Android, iOS doesn't have the ability to "see" other applications by viewing the installed packages. However iOS does have the ability to launch other applications though web commands. Which is achieved through by an app with the "CFBundleURLSchemes" in the [Info.plist](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/AboutInformationPropertyListFiles.html).

My plugin is designed to read the receiving end of this, however your application need to know which applications you are searching for before hand. This is what the "LSApplicationQueriesSchemes" is for. For example if you want to search for YouTube you will need to find the url string that the  YouTube application will respond to.

You can test this out in Safari.

As for which applications responds to which LSApplicationQueriesSchemes, I haven't the faintest clue. But I am certain you can search for it.
